#!/bin/bash
# Exports nodes from a workflow
#
# Copyright (C) 2019 Daniel H. Huson
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [ $# == 0 ]
then
	options="-h"
else
	options=$*
fi	

bin_dir=`dirname "$0"`       # may be relative path
bin_dir=`cd "$bin_dir" && pwd`    # ensure absolute path
jars_dir="$bin_dir/../jars"

jre_dir=${installer:sys.preferredJre}

if [ -z $jre_dir ]
then
	java=java
	vmOptions="-Xmx12G"
	classpath="$jars_dir/Jama-1.0.3.jar:$bin_dir/../antbuild/SplitsTree5.jar:"
else
	java=$jre_dir/bin/java
	vmOptions=`grep "^-" $bin_dir/../SplitsTree5.vmoptions`
	classpath="$jars_dir/Jama-1.0.3.jar:$jars_dir/SplitsTree5.jar:"
fi

java_flags="-server -Duser.language=en -Duser.region=US -Djava.awt.headless=true $vmOptions"

$java $java_flags -cp "$classpath" splitstree5.tools.ExportWorkflow  $options
