module splitstreefive {
    requires transitive jloda;
    requires transitive javafx.controls;
    requires transitive javafx.graphics;
    requires transitive javafx.fxml;
    requires transitive java.sql;
    requires transitive java.desktop;

    requires junit;
    requires Jama;
    requires richtextfx.fat;
    requires fx.platform.utils;
    requires com.install4j.runtime;

    exports splitstree5.resources.css;
    exports splitstree5.resources.icons;
    exports splitstree5.resources.images;

    opens splitstree5.resources.css;
    opens splitstree5.resources.icons;
    opens splitstree5.resources.images;

    exports splitstree5.core;
    exports splitstree5.core.algorithms;
    exports splitstree5.core.algorithms.characters2distances;
    exports splitstree5.core.algorithms.characters2network;
    exports splitstree5.core.algorithms.characters2splits;
    exports splitstree5.core.algorithms.distances2network;
    exports splitstree5.core.algorithms.distances2splits;
    exports splitstree5.core.algorithms.distances2trees;
    exports splitstree5.core.algorithms.filters;
    exports splitstree5.core.algorithms.interfaces;
    exports splitstree5.core.algorithms.splits2splits;
    exports splitstree5.core.algorithms.splits2trees;
    exports splitstree5.core.algorithms.trees2distances;
    exports splitstree5.core.algorithms.trees2splits;
    exports splitstree5.core.algorithms.trees2trees;
    exports splitstree5.core.algorithms.views;
    exports splitstree5.core.analysis;
    exports splitstree5.core.datablocks;
    exports splitstree5.core.datablocks.characters;
    exports splitstree5.core.misc;
    exports splitstree5.core.models;
    exports splitstree5.core.models.nucleotideModels;
    exports splitstree5.core.models.proteinModels;
    exports splitstree5.core.topfilters;
    exports splitstree5.core.workflow;
    exports splitstree5.dialogs;
    exports splitstree5.dialogs.exporter;
    exports splitstree5.dialogs.importer;
    exports splitstree5.dialogs.message;
    exports splitstree5.gui;
    exports splitstree5.gui.algorithmtab;
    exports splitstree5.gui.algorithmtab.next;
    exports splitstree5.gui.algorithmtab.rootbyoutgroup;
    exports splitstree5.gui.algorithmtab.taxafilterview;
    exports splitstree5.gui.algorithmtab.treefilterview;
    exports splitstree5.gui.algorithmtab.treeselector;
    exports splitstree5.gui.datatab;
    exports splitstree5.gui.editinputtab;
    exports splitstree5.gui.editinputtab.collapsing;
    exports splitstree5.gui.editinputtab.highlighters;
    exports splitstree5.gui.formattab;
    exports splitstree5.gui.formattab.fontselector;
    exports splitstree5.gui.graph3dtab;
    exports splitstree5.gui.graphtab;
    exports splitstree5.gui.graphtab.base;
    exports splitstree5.gui.graphtab.commands;
    exports splitstree5.gui.inputtab;
    exports splitstree5.gui.methodstab;
    exports splitstree5.gui.texttab;
    exports splitstree5.gui.utils;
    exports splitstree5.gui.workflowtab;
    exports splitstree5.gui.workflowtree;
    exports splitstree5.info;
    exports splitstree5.io.exports;
    exports splitstree5.io.exports.interfaces;
    exports splitstree5.io.imports;
    exports splitstree5.io.imports.NeXML;
    exports splitstree5.io.imports.interfaces;
    exports splitstree5.io.imports.nexus;
    exports splitstree5.io.imports.utils;
    exports splitstree5.io.nexus;
    exports splitstree5.io.nexus.graph;
    exports splitstree5.io.nexus.stateLabeler;
    exports splitstree5.io.nexus.utils;
    exports splitstree5.io.nexus.workflow;
    exports splitstree5.main;
    exports splitstree5.menu;
    exports splitstree5.toolbar;
    exports splitstree5.tools;
    exports splitstree5.utils;
    exports splitstree5.xtra;
    exports splitstree5.xtra.align;

    opens splitstree5.dialogs.exporter;
    opens splitstree5.dialogs.importer;
    opens splitstree5.dialogs.message;
    opens splitstree5.gui.algorithmtab;
    opens splitstree5.gui.algorithmtab.rootbyoutgroup;
    opens splitstree5.gui.algorithmtab.taxafilterview;
    opens splitstree5.gui.algorithmtab.treefilterview;
    opens splitstree5.gui.algorithmtab.treeselector;
    opens splitstree5.gui.formattab;
    opens splitstree5.gui.formattab.fontselector;
    opens splitstree5.gui.workflowtab;
    opens splitstree5.main;
    opens splitstree5.menu;
    opens splitstree5.toolbar;
    opens splitstree5.xtra.align;
}